version: 2
defaults: &defaults
  docker:
    - image: circleci/node:14
  working_directory: ~/repo

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test
      - run: echo Hello Pluralsight

workflows:
  version: 2
  test:
    jobs:
      - install
      - build:
          requires:
            - install
